FROM docker.m.daocloud.io/library/python:3.12-slim

COPY torch-2.5.1+cpu-cp312-cp312-linux_x86_64.whl /tmp/torch-wheels/

RUN pip install --no-deps /tmp/torch-wheels/torch-2.5.1+cpu-cp312-cp312-linux_x86_64.whl && \
    rm -rf /tmp/torch-wheels
